Vagrant.configure(2) do |config|
  # config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :rep01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.71"
    ### hostname of server
    server.vm.hostname = 'repcached01'
    ### box setting
    server.vm.box = "bento/centos-6.7"
    ### vm setting
    server.vm.provider "virtualbox" do |vb|
      ### name of virtualbox
      vb.name = "repcached01"
      ### spec define
      vb.customize ['modifyvm', :id,"--memory", 1024]
      vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
      vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
    end
    ### settitng of synced_folder
    server.vm.synced_folder "../../", "/develop/repcached", \
      :create => true, \
      :owner  => 'vagrant', \
      :group  => 'vagrant', \
      :mount_options => ['dmode=755,fmode=755']
    server.vm.provision :shell, inline: "/bin/bash /develop/repcached/opsfiles/vagrant/provision.sh rep01"
  end

  config.vm.define :rep02 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.72"
    ### hostname of server
    server.vm.hostname = 'repcached02'
    ### box setting
    server.vm.box = "bento/centos-6.7"
    ### vm setting
    server.vm.provider "virtualbox" do |vb|
      ### name of virtualbox
      vb.name = "repcached02"
      ### spec define
      vb.customize ['modifyvm', :id,"--memory", 1024]
      vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
      vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
    end
    ### settitng of synced_folder
    server.vm.synced_folder "../../", "/develop/repcached", \
      :create => true, \
      :owner  => 'vagrant', \
      :group  => 'vagrant', \
      :mount_options => ['dmode=755,fmode=755']
    server.vm.provision :shell, inline: "/bin/bash /develop/repcached/opsfiles/vagrant/provision.sh rep02"
  end
end
